### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'detach'   metric_for_best_model change "loss" to "f1"

### ISSUE THREAD

**Issue by yuxuan2015** [WeiNyn/DIETClassifier-pytorch#5]
![企业微信截图_16337656213244](https://user-images.githubusercontent.com/15645056/136649396-34ac746b-6176-49e2-b1d0-3e758d82c2c2.png)

![computer_metrics](https://user-images.githubusercontent.com/15645056/136649490-4a58f309-aa27-487a-8609-5a9a560db112.png)

tensors is None
the type of tensors is <class 'NoneType'>
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    trainer.train()
  File "/data1/Semantic_team/chatbot/DIET/DIETClassifier-pytorch/src/models/trainer.py", line 77, in train
    self.trainer.train()
  File "/data1/anaconda3/envs/diet_py36/lib/python3.6/site-packages/transformers/trainer.py", line 935, in train
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)
  File "/data1/anaconda3/envs/diet_py36/lib/python3.6/site-packages/transformers/trainer.py", line 1004, in _maybe_log_save_evaluate
    metrics = self.evaluate()
  File "/data1/anaconda3/envs/diet_py36/lib/python3.6/site-packages/transformers/trainer.py", line 1449, in evaluate
    metric_key_prefix=metric_key_prefix,
  File "/data1/anaconda3/envs/diet_py36/lib/python3.6/site-packages/transformers/trainer.py", line 1566, in prediction_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/data1/anaconda3/envs/diet_py36/lib/python3.6/site-packages/transformers/trainer.py", line 1695, in prediction_step
    logits = nested_detach(logits)
  File "/data1/anaconda3/envs/diet_py36/lib/python3.6/site-packages/transformers/trainer_pt_utils.py", line 106, in nested_detach
    return type(tensors)(nested_detach(t) for t in tensors)
  File "/data1/anaconda3/envs/diet_py36/lib/python3.6/site-packages/transformers/trainer_pt_utils.py", line 106, in <genexpr>
    return type(tensors)(nested_detach(t) for t in tensors)
  File "/data1/anaconda3/envs/diet_py36/lib/python3.6/site-packages/transformers/trainer_pt_utils.py", line 107, in nested_detach
    return tensors.detach()
AttributeError: 'NoneType' object has no attribute 'detach'

**Comment by WeiNyn** [comment]
tks for your information, I don't know the cause of this error, so I added a little note for this issue in the readme

**Comment by luckystar1992** [comment]
Facing the same issue with > 4.2, now the issue is File "***site-packages/transformers/trainer_pt_utils.py", line 48, in torch_pad_and_concatenate
if len(tensor1.shape) == 1 or tensor1.shape[1] == tensor2.shape[1]:
IndexError: tuple index out of range

In the forward() function in classifier.py it returns loss, but the loss tensor's shape is 0, so it leads the above Error.
